
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ascii-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<diaglviv>/AsciiArtify'
    targetRevision: main
    path: deploy/demo-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true